In [7]:
from PIL import Image
import os, sys
import cv2
import numpy as np

'''
Converts all images in a directory to '.npy' format.
Use np.save and np.load to save and load the images.
Use it for training your neural networks in ML/DL projects. 
'''

# Path to image directory
path = "E:/D&C/Images/"
dirs = os.listdir( path )
dirs.sort()
x_train=[]

def load_dataset():
    # Append images to a list
    for item in dirs:
        if os.path.isfile(path+item):
            im = Image.open(path+item)
            im = np.array(im)
            x_train.append(im)

if __name__ == "__main__":
    
    load_dataset()
    
    # Convert and save the list of images in '.npy' format
    imgset=np.array(x_train)
    np.save("coe_faces.npy",imgset)

AttributeError: max

In [6]:
t = np.load('coe_faces.npy')
print(t)

[[[ 92 101 139 ... 145 135 116]
  [ 94 109 152 ... 111 138 125]
  [105 125 172 ...  95 137 138]
  ...
  [155 151 145 ...  96 102 105]
  [155 153 144 ...  94  97  97]
  [155 154 144 ...  92  93  90]]

 [[ 42  31  13 ... 162 161 162]
  [ 30  33  28 ... 161 163 165]
  [ 43  40  35 ... 162 162 163]
  ...
  [103  96 105 ... 121 123 125]
  [147 119 139 ... 116 119 122]
  [150 147 132 ... 111 115 119]]

 [[ 79  83  72 ... 109 140 127]
  [ 81  83  73 ... 105 120 131]
  [ 80  81  73 ... 153  91 133]
  ...
  [ 97  97  98 ... 178 178 185]
  [ 98  98  99 ... 189 186 189]
  [ 98  99 100 ... 196 188 187]]

 ...

 [[  8   6  13 ...   5   4   0]
  [  8   4  16 ...   0   0   0]
  [  5   2  17 ...   0   0   3]
  ...
  [128 129 132 ... 114 113 112]
  [122 130 127 ... 114 113 113]
  [124 132 123 ... 114 112 112]]

 [[  0   0   0 ...  24  17   9]
  [  1   0   0 ...  27  23  17]
  [  1   1   1 ...  41  34  26]
  ...
  [134 119 118 ...  60  64  67]
  [125 140 155 ...  43  47  48]
  [138 159 177 ...  47  45  